path: M:\VK_ML_tech_task\yolo_dataset

train: images/train  # Относительно path
val: images/val      # Относительно path

nc: 1
names: ['logo']

# Аугментации
augment: True
hsv_h: 0.015  # Изменение оттенка
hsv_s: 0.7    # Изменение насыщенности
hsv_v: 0.4    # Изменение яркости
degrees: 10   # Поворот на ±10 градусов
translate: 0.1  # Сдвиг на 10%
scale: 0.5    # Масштабирование на 50%
shear: 0.2    # Наклон на ±20%
flipud: 0.0   # Отражение по вертикали
fliplr: 0.5   # Отражение по горизонтали (50% вероятности)
mosaic: 1.0   # Мозаика (100% вероятности)
mixup: 0.1    # Mixup (10% вероятности)